export const authActionTypes = {
    SET_REGISTER_USER: 'SET_REGISTER_USER',
    SET_CURREN_USER: 'SET_CURREN_USER'
}

export const chatActionTypes = {
    SET_MESSAGES: 'SET_MESSAGES',
    SET_ACTIVE_ROOM: 'SET_ACTIVE_ROOM',
    REMOVE_ROOM: 'REMOVE_ROOM',
    SET_ROOMS: 'SET_ROOMS',
    ADD_ROOM: 'ADD_ROOM'
}